# 00. PyTorch Fundamentals Exercises

### 1. Documentation reading 

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):
  * The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
  * The documentation on [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).

[Exercises Notebooks](https://github.com/mrdbourke/pytorch-deep-learning/tree/main/extras/exercises)

[Solutions Notebooks](https://github.com/mrdbourke/pytorch-deep-learning/tree/main/extras/solutions)


In [1]:
# No code solution (reading)

### 2. Create a random tensor with shape `(7, 7)`.


In [2]:
# Import torch

import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

print(torch.__version__)
## Check if CUDA is available:
print("CUDA available:", torch.cuda.is_available())

## set pytorch tensor / device to use GPU
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print("Using device:", device)
### tensor = tensor.to(device) to move tensor to GPU


# Create random tensor
random_tensor = torch.rand(size=(7, 7)) 
print(f"random_tensor", random_tensor, f"; dtype: {random_tensor.dtype}", f"; shape: {random_tensor.shape}", f"; device: {random_tensor.device} \n")

2.5.1
CUDA available: True
Using device: cuda
random_tensor tensor([[0.1648, 0.5081, 0.1077, 0.0202, 0.4203, 0.7297, 0.3799],
        [0.0677, 0.7581, 0.9525, 0.9202, 0.3000, 0.0724, 0.5431],
        [0.2676, 0.3118, 0.0584, 0.2295, 0.2004, 0.3127, 0.1098],
        [0.1124, 0.0444, 0.2263, 0.7749, 0.8635, 0.5983, 0.1712],
        [0.0052, 0.3440, 0.2070, 0.0765, 0.7499, 0.9484, 0.5351],
        [0.5176, 0.2780, 0.4953, 0.0923, 0.1487, 0.1188, 0.8706],
        [0.8644, 0.2131, 0.4707, 0.9488, 0.6270, 0.2904, 0.2944]]) ; dtype: torch.float32 ; shape: torch.Size([7, 7]) ; device: cpu 



### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [5]:
torch.rand(size=(1, 7)).T

tensor([[0.7216],
        [0.9575],
        [0.0669],
        [0.0467],
        [0.2640],
        [0.1276],
        [0.9788]])

In [7]:
# Create another random tensor
random_tensor_2 = torch.rand(size=(1, 7))
# Perform matrix multiplication 
torch.matmul(random_tensor, random_tensor_2.T)

tensor([[2.2582],
        [1.5082],
        [2.5158],
        [1.6808],
        [1.5308],
        [2.8808],
        [2.2336]])

### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [3]:
# Set manual seed
torch.manual_seed(seed = 0)

# Create two random tensors
random_tensor = torch.rand(size=(7, 7)) 
random_tensor_2 = torch.rand(size=(1, 7))
# Matrix multiply tensors
matmul = torch.matmul(random_tensor, random_tensor_2.T) 
print(f"random_tensor", matmul, f"; dtype: {matmul.dtype}", f"; shape: {matmul.shape}", f"; device: {matmul.device} \n")


random_tensor tensor([[1.8542],
        [1.9611],
        [2.2884],
        [3.0481],
        [1.7067],
        [2.5290],
        [1.7989]]) ; dtype: torch.float32 ; shape: torch.Size([7, 1]) ; device: cpu 



### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [ ]:
# Set random seed on the GPU
# Set manual seed
torch.cuda.manual_seed(seed = 1234)

random_tensor tensor([[0.9558],
        [1.2227],
        [0.9335],
        [1.6030],
        [0.9344],
        [0.5282],
        [0.5664]], device='cuda:0') ; dtype: torch.float32 ; shape: torch.Size([7, 1]) ; device: cuda:0 




### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [21]:
# Set random seed on cuda
torch.manual_seed(seed = 1234)
# torch.cuda.manual_seed(seed = 1234)
# random_tensor = torch.rand(size=(2,3), device = "cuda")
# random_tensor_2 = torch.rand(size=(1, 7), device = "cuda")

# Check for access to GPU
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print("Using device:", device)

# Create two random tensors on GPU
random_tensor = torch.rand(size=(2,3)).to(device)
random_tensor_2 = torch.rand(size=(2,3)).to(device)
## M2:
# random_tensor = torch.rand(size=(2,3), device = "cuda")
# random_tensor_2 = torch.rand(size=(1, 7), device = "cuda")

print(f"random_tensor", random_tensor, f"; dtype: {random_tensor.dtype}", f"; shape: {random_tensor.shape}", f"; device: {random_tensor.device} \n")
print(f"random_tensor 2", random_tensor_2, f"; dtype: {random_tensor_2.dtype}", f"; shape: {random_tensor_2.shape}", f"; device: {random_tensor_2.device} \n")


Using device: cuda
random_tensor tensor([[0.0290, 0.4019, 0.2598],
        [0.3666, 0.0583, 0.7006]], device='cuda:0') ; dtype: torch.float32 ; shape: torch.Size([2, 3]) ; device: cuda:0 

random_tensor 2 tensor([[0.0518, 0.4681, 0.6738],
        [0.3315, 0.7837, 0.5631]], device='cuda:0') ; dtype: torch.float32 ; shape: torch.Size([2, 3]) ; device: cuda:0 




### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [22]:
# Perform matmul on tensor_A and tensor_B
matmul = torch.matmul(random_tensor, random_tensor_2.T) 
print(f"random_tensor", matmul, f"; dtype: {matmul.dtype}", f"; shape: {matmul.shape}", f"; device: {matmul.device} \n")

random_tensor tensor([[0.3647, 0.4709],
        [0.5184, 0.5617]], device='cuda:0') ; dtype: torch.float32 ; shape: torch.Size([2, 2]) ; device: cuda:0 



### 8. Find the maximum and minimum values of the output of 7.

In [23]:
# Find max
print(f"max matmul", matmul.max(), "\n")

# Find min
print(f"min matmul", matmul.min(), "\n")

max matmul tensor(0.5617, device='cuda:0') 

min matmul tensor(0.3647, device='cuda:0') 



### 9. Find the maximum and minimum index values of the output of 7.

In [25]:
# Find arg max
print(f"argmax matmul (i.e. index where max)", matmul.argmax(), "\n")

# Find arg min
print(f"argmin matmul (i.e. index where min)", matmul.argmin(), "\n")

argmax matmul (i.e. index where max) tensor(3, device='cuda:0') 

argmin matmul (i.e. index where min) tensor(0, device='cuda:0') 




### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [38]:
# Set seed
torch.manual_seed(seed = 7)

# Create random tensor
random_tensor = torch.rand(size=(1,1,1,10))
print(f"random_tensor", random_tensor, f"; dtype: {random_tensor.dtype}", f"; shape: {random_tensor.shape}", f"; device: {random_tensor.device} \n")

# Remove single dimensions
random_tensor_squeezed = torch.squeeze(random_tensor)
print(f"random_tensor_squeezed", random_tensor_squeezed, f"; dtype: {random_tensor_squeezed.dtype}", f"; shape: {random_tensor_squeezed.shape}", f"; device: {random_tensor_squeezed.device} \n")

# Print out tensors and their shapes


random_tensor tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) ; dtype: torch.float32 ; shape: torch.Size([1, 1, 1, 10]) ; device: cpu 

random_tensor_squeezed tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) ; dtype: torch.float32 ; shape: torch.Size([10]) ; device: cpu 

